version: "3.8"

services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    environment:
      TZ: America/New_York
      PUID: "1000"
      PGID: "1000"
      WEBUI_PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - /mnt/downloads:/downloads
    restart: unless-stopped

