version: "3.8"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    environment:
      TZ: 'America/New_York'
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_SCHEDULE: "${WATCHTOWER_SCHEDULE}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped