version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      VIRTUAL_HOST: 'hped1.jsnouff.net'
      TZ: 'America/New_York'
      WEBPASSWORD: 'boom'
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^http://hped1.jsnouff.net/$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=http://hped1.jsnouff.net/admin"
      - "traefik.http.routers.pihole.rule=Host(`hped1.jsnouff.net`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.middlewares=pihole-redirect"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
