version: "3.3"

services:
#   ide:
#     image: psharkey/intellij:latest
# #    image: psharkey/netbeans-8.1:latest
#     environment:
#       - DISPLAY=novnc:0.0
#     depends_on:
#       - novnc
#     networks:
#       - x11
  novnc:
    container_name: novnc
    image: consol/rocky-xfce-vnc
    network_mode: "host"
    privileged: true
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - DISPLAY=:99
    ports:
      - "6901:6901"
      - "5901:5901"
    volumes:
      - "$HOME/.Xauthority:/headless/.Xauthority:rw"
      - /tmp/.X11-unix:/tmp/.X11-unix
#     networks:
#       - x11
# networks:
#   x11: