services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:latest
    entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    environment:
      TZ: 'America/New_York'
    volumes:
      - ./data:/app/pb_data
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: curl -fs "http://localhost:5000/api/health" || exit 1
      interval: 10s