version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      VIRTUAL_HOST: '${PIHOLE_DOMAIN_NAME}'
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEBPASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^https://${PIHOLE_DOMAIN_NAME}/$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=https://${PIHOLE_DOMAIN_NAME}/admin"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_DOMAIN_NAME}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.middlewares=pihole-redirect"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true