version: "3.3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      VIRTUAL_HOST: 'hped1.jsnouff.net'
      TZ: 'America/New_York'
      WEBPASSWORD: ${WEBPASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.regex=^http://pihole.jsnouff.net/$"
      - "traefik.http.middlewares.pihole-redirect.redirectregex.replacement=http://pihole.jsnouff.net/admin"
      - "traefik.http.routers.pihole.rule=Host(`pihole.jsnouff.net`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.middlewares=pihole-redirect"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true